export const types = {
  FETCH_STATUS: 'FETCH_STATUS',
  FETCH_SUCCESS: 'FETCH_SUCCESS',
  FETCH_ERROR: 'FETCH_ERROR',

  IMAGE_STATUS: 'IMAGE_STATUS',
  IMAGE_SUCCESS: 'IMAGE_SUCCESS',
  IMAGE_ERROR: 'IMAGE_ERROR',
};
